diff -Naur truecrypt-7.0a-source.orig/Makefile truecrypt-7.0a-source/Makefile
--- truecrypt-7.0a-source.orig/Makefile	2011-01-25 23:07:25.326000016 +0200
+++ truecrypt-7.0a-source/Makefile	2011-01-25 23:10:55.734000016 +0200
@@ -35,13 +35,13 @@
 export AS := nasm
 export RANLIB ?= ranlib
 
-export CFLAGS := -Wall
-export CXXFLAGS := -Wall -Wno-unused-parameter
+export CFLAGS :+= -Wall
+export CXXFLAGS :+= -Wall -Wno-unused-parameter
 C_CXX_FLAGS := -MMD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -I$(BASE_DIR) -I$(BASE_DIR)/Crypto
 export ASFLAGS := -Ox -D __GNUC__
-export LFLAGS :=
+export LFLAGS :=$(LDFLAGS)
 
-export PKG_CONFIG_PATH ?= /usr/local/lib/pkgconfig
+export PKG_CONFIG_PATH ?= /usr/lib/pkgconfig
 
 export WX_CONFIG ?= wx-config
 export WX_CONFIG_ARGS := --unicode
