#!/bin/sh

# Simple script to set regulatory domain.
# Derived by Fedora, simplified for Pardus
# 2009

TIMEZONERC=/etc/timezone
TIMEZONE=

if [ -f $TIMEZONERC ]
then
	# This should set TIMEZONE
	TIMEZONE=$(cat $TIMEZONERC 2>/dev/null)
else
	echo "Timezone information not found!  Unable to set regulatory domain."
	exit
fi

if [ -z "$TIMEZONE" ]
then
	echo "Timezone information not set!  Unable to set regulatory domain."
	exit
fi

COOKED_ZONE=$(echo $TIMEZONE | sed -e 's/ /_/')

COUNTRY=$(grep $COOKED_ZONE /usr/share/zoneinfo/zone.tab | awk '{ print $1 }')

if [ -z "$COUNTRY" ]
then
	echo "Could not determine country!  Unable to set regulatory domain."
	exit
fi

iw reg set $COUNTRY
