--- sdricoh_cs-0.1.3/Makefile.org	2008-05-01 17:18:08.000000000 +0300
+++ sdricoh_cs-0.1.3/Makefile	2008-05-01 17:18:39.000000000 +0300
@@ -10,7 +10,6 @@
 install:
 	if test ! -d $(DESTDIR)$(MDIR) ; then mkdir -p $(DESTDIR)$(MDIR) ; fi
 	install -D -m 644 *.ko $(DESTDIR)$(MDIR)
-	depmod -a
 
 clean:
 	rm -f *.o *.ko *.mod.c .*o.cmd .*o.d .*o.flags Module.symvers

--- sdricoh_cs-0.1.3/sdricoh_cs.c.org	2008-05-01 17:13:53.000000000 +0300
+++ sdricoh_cs-0.1.3/sdricoh_cs.c	2008-05-01 17:14:50.000000000 +0300
@@ -328,7 +328,7 @@
 			cmd->error = 0;
 			mmc_request_done(mmc, mrq);
 			return;
-		case MMC_SEND_EXT_CSD:
+		/*case MMC_SEND_EXT_CSD:
 			cmd->error = -EINVAL;
 			mmc_request_done(mmc, mrq);
 			return;
