--- Makefile.orig	2006-10-19 10:41:49.000000000 +0300
+++ Makefile	2006-10-25 21:22:08.380455068 +0300
@@ -18,12 +18,12 @@
 
 # Where to install things:
 
-PREFIX=/usr/local
+PREFIX=/usr
 
 
 # Root directory to place files when creating packages.
 
-PKG_ROOT=
+#PKG_ROOT=
 
 
 # Program:
@@ -1034,7 +1034,7 @@
 		$^ \
 		$(HQXX_O) \
 		$(SDL_LIBS) \
-		-lm $(ARCH_LINKS)
+		-lm -lpng12 $(ARCH_LINKS)
 	@$(RSRC_CMD)
 	@$(MIMESET_CMD)
 
