--- client/Makefile.orig	2009-06-15 13:28:44.000000000 +0300
+++ client/Makefile	2009-06-15 13:23:41.000000000 +0300
@@ -1,8 +1,8 @@
 PO_FILES=$(wildcard po/*.po)
 MO_FILES=$(patsubst %.po,%.mo,$(PO_FILES))
-PY_FILES=fs_util.py deleteProfile.py haldump.py __init__.py sendProfile.py smoltGui.py smolt.py software.py smoltFirstBoot.py gui.py privacypolicy.py scan.py
+PY_FILES=fs_util.py deleteProfile.py haldump.py __init__.py sendProfile.py smolt.py software.py smoltFirstBoot.py privacypolicy.py scan.py
 DIRED_MO_FILES=$(patsubst po/%.mo,mo/%/LC_MESSAGES/$(NAME).mo,$(MO_FILES))
-CLIENT_FILES=fs_util.py deleteProfile.py gui.py haldump.py i18n.py privacypolicy.py sendProfile.py smolt.py smoltGui.py software.py scan.py
+CLIENT_FILES=fs_util.py deleteProfile.py haldump.py i18n.py privacypolicy.py sendProfile.py smolt.py software.py scan.py os_detect.py
 
 
 NAME=smolt
@@ -58,16 +58,11 @@
 	
 	gzip -9 man/smoltSendProfile.1 > $(DATADIR)/man/man1/smoltSendProfile.1.gz
 	gzip -9 man/smoltDeleteProfile.1 > $(DATADIR)/man/man1/smoltDeleteProfile.1.gz
-	gzip -9 man/smoltGui.1 > $(DATADIR)/man/man1/smoltGui.1.gz
 	
-	ln -sf $(DATADIR)/$(NAME)/client/sendProfile.py $(BINDIR)/smoltSendProfile
-	ln -sf $(DATADIR)/$(NAME)/client/deleteProfile.py $(BINDIR)/smoltDeleteProfile
-	ln -sf $(DATADIR)/$(NAME)/client/smoltGui.py $(BINDIR)/smoltGui
 	
 	chmod +x $(DATADIR)/$(NAME)/client/*Profile.py
-	chmod +x $(DATADIR)/$(NAME)/client/smoltGui.py
 	
-	desktop-file-install --vendor='fedora' --dir=$(DATADIR)/applications ./smolt.desktop
+
 	
 move-mo: $(DIRED_MO_FILES)
 	
@@ -75,14 +70,7 @@
 	mkdir -p mo/$*/LC_MESSAGES/
 	cp $< $@
 
-install: post-install
-
-post-install: install-main
-
-	mkdir -p $(ETC)/init.d/
-	mkdir -p $(ETC)/cron.d/
-	cp -adv smolt-init $(ETC)/init.d/smolt
-	cp -adv smolt.cron.monthly $(ETC)/cron.d/smolt
+install: install-main
 	
 uuid:
 	python makeuuid.py $(SMOLTCONFIGDIR)/hw-uuid True
