diff -Nur glob2-0.8.21-old/data/icons/Makefile.in glob2-0.8.21/data/icons/Makefile.in
--- glob2-0.8.21-old/data/icons/Makefile.in	2006-09-03 02:19:24.630082336 +0300
+++ glob2-0.8.21/data/icons/Makefile.in	2006-09-03 02:20:05.703838176 +0300
@@ -168,7 +168,7 @@
 target_cpu = @target_cpu@
 target_os = @target_os@
 target_vendor = @target_vendor@
-glob2icondir = $(datadir)/pixmaps
+glob2icondir = /usr/share/pixmaps
 glob2icon_DATA = $(wildcard $(srcdir)/*.png) 
 EXTRA_DIST = $(glob2icon_DATA)
 all: all-am
diff -Nur glob2-0.8.21-old/data/Makefile.in glob2-0.8.21/data/Makefile.in
--- glob2-0.8.21-old/data/Makefile.in	2006-09-03 02:19:22.247444552 +0300
+++ glob2-0.8.21/data/Makefile.in	2006-09-03 02:19:50.505148728 +0300
@@ -182,7 +182,7 @@
 SUBDIRS = fonts gfx gui zik icons
 glob2datadir = $(pkgdatadir)/data
 glob2data_DATA = $(wildcard $(srcdir)/*.txt)
-glob2linkdir = $(datadir)/applications
+glob2linkdir = /usr/share/applications
 glob2link_DATA = glob2.desktop
 EXTRA_DIST = $(glob2data_DATA) $(glob2link_DATA)
 all: all-recursive
