#!/bin/bash

db_file=$1
tmp_file=`mktemp --suffix=bugzilla`
real_dump=$tmp_file
file_extension=${db_file##*.}
db_pass=$(grep db_pass /etc/bugzilla/localconfig|sed -e "s:^\$db_pass.*=.*'\(.*\)';$:\1:")

if [ -z $db_file ]; then
    echo "Usage: $0 <path-to-db-dump>"
    exit 1
fi

if [ -z $db_pass ]; then
    echo "You have to set your db_pass in /etc/bugzilla/localconfig"
    exit 1
fi

if [ ! -S /var/run/mysqld/mysqld.sock ]; then
    echo "It seems that MySQL is not running, exiting."
    exit 1
fi

if [ "$file_extension" = "lzma" -o "$file_extension" = "xz" ]; then
    echo "Uncompressing LZMA/XZ dump.."
    xz -d -k -v -c $db_file > $real_dump
elif [ "$file_extension" = "gz" ]; then
    echo "Uncompressing GZ dump.."
    gunzip -v -c $db_file > $real_dump
elif [ "$file_extension" = "bz2" ]; then
    echo "Uncompressing BZ2 dump.."
    bunzip -d -k -v -c $db_file > $real_dump
else
    real_dump=$db_file
fi

echo "Restoring from $real_dump.. "
mysql -u bugs -p$db_pass bugs < $real_dump

unset db_pass
rm -rf $tmp_file
