#!/bin/bash

# Update bugzilla templates and icons
for d in icons template/en template/tr; do
    svn up /var/www/bugzilla.pardus.org.tr/bugzilla/$d &> /dev/null
done

#cd /var/www/bugzilla.pardus.org.tr/bugzilla/
#./collectstats.pl 1>&2

# Update components responsibles for the review product
#/var/www/bugzilla.pardus.org.tr/scripts/bugzilla/update-components-for-review 1>&2
