#! /bin/sh
#
# The startup wrapper for akia

ARCH=`uname -m`

if [ -z "${JAVA_HOME}" ] ; then
	JAVA_HOME=/opt/sun-jdk
fi

JAVA_BIN=${JAVA_HOME}/bin/java

if [ "x$ARCH" == "xx86_64" ]; then
    JAVA_BIN=${JAVA_HOME}/bin/java
fi

if [ ! -x ${JAVA_BIN} ] ; then
	echo "Failed to find executable '${JAVA_BIN}'" > /dev/stderr
	exit -1
fi

AKIA_JAR=/usr/share/akia/akia.jar
AKIA_RUN="${JAVA_BIN} -jar ${AKIA_JAR}"

if [ ! -f ${AKIA_JAR} ] ; then
   echo "Failed to find library '${AKIA_JAR}'" > /dev/stderr
   exit -1
fi

${AKIA_RUN} -Dsun.security.smartcardio.library=/usr/lib/libpcsclite.so $@
