--- src/Makefile.in.orig	2007-11-19 15:45:35.000000000 +0200
+++ src/Makefile.in	2007-11-19 20:14:11.000000000 +0200
@@ -257,8 +257,8 @@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 NULL = 
-gamesdir = $(prefix)/games
-scoredir = /var/games/tecnoballz
+gamesdir = $(prefix)/bin
+scoredir = /var/lib/games/tecnoballz
 score = tecnoballz.hi
 SUBDIRS = TecnoballZ 
 tecnoballz_SOURCES = $(SOURCES_MAIN) 
