#!/bin/sh

if [ "$#" -eq 0 ]
then
    mplayer tv:// -tv driver=v4l:device=/dev/video0:width=640:height=480:noaudio -x 800 -y 600 -vf-add pp=hb:a/vb:a,hqdn3d,mirror
else
    mplayer tv:// -tv driver=v4l:device=/dev/$1:width=640:height=480:noaudio -x 800 -y 600 -vf-add pp=hb:a/vb:a,hqdn3d,mirror
fi
