#!/bin/sh
# Support script to properly set environments for Designer with Jambi to run

export QTDIR=/usr/qt/4
export LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH
export PATH=/usr/qt/4/bin:$PATH
export JAVADIR=/opt/sun-jre
export CLASSPATH=/usr/share/java/qtjambi.jar

export MOC=/usr/qt/4/bin/moc
export UIC=/usr/qt/4/bin/juic

exec /usr/qt/4/bin/designer "$@"
