#!/bin/sh
# Support script to properly set environments for Launcher

export QTDIR=/usr/qt/4
export LD_LIBRARY_PATH=/usr/qt/4/lib:$LD_LIBRARY_PATH
export PATH=/usr/qt/4/bin:$PATH
export JAVADIR=/opt/sun-jre

cd /usr/share/doc/qtjambi-4.3.1-1
java -cp /usr/share/java/qtjambi.jar:. com.trolltech.launcher.Launcher
