#!/bin/bash

MAIN="rrgbis"

DATADIR="/usr/share/$MAIN"

TARGET="$HOME/.$MAIN"

TOCOPY="settings.dat"

if [ ! -e "$TARGET" ]; then
        mkdir "$TARGET"
fi
if [ ! -e "$TARGET/settings.dat" ] ; then
        cp "$DATADIR/settings.dat" "$TARGET/"
fi

exec /usr/bin/rrgbis.bin "$@"
