--- rxvt-unicode-8.6/doc/Makefile.in.org	2007-11-24 14:36:09.000000000 +0200
+++ rxvt-unicode-8.6/doc/Makefile.in	2007-11-24 15:57:13.000000000 +0200
@@ -76,7 +76,7 @@
 	rxvt.1.txt    rxvt.7.txt    rxvtc.1.txt    rxvtd.1.txt    rxvtperl.3.txt \
 	rxvt.1.html   rxvt.7.html   rxvtc.1.html   rxvtd.1.html   rxvtperl.3.html \
 	../README.configure ../README.FAQ
-	infocmp -C rxvt-unicode >$(srcdir)/etc/rxvt-unicode.termcap
+#	infocmp -C rxvt-unicode >$(srcdir)/etc/rxvt-unicode.termcap
 
 clean:
 	rm -f *~
@@ -103,7 +103,7 @@
 	$(INSTALL_DATA) rxvt.7.man  $(DESTDIR)$(man7dir)/$(RXVTNAME).$(man7ext)
 @IF_PERL@	$(INSTALL) -d $(DESTDIR)$(man3dir)
 @IF_PERL@	$(INSTALL_DATA) rxvtperl.3.man $(DESTDIR)$(man3dir)/$(RXVTNAME)perl.$(man3ext)
-	@TIC@ $(srcdir)/etc/rxvt-unicode.terminfo
+#	@TIC@ $(srcdir)/etc/rxvt-unicode.terminfo
 
 distdepend: alldoc
 
