diff -Nur ebtables-v2.0.8-2-old/Makefile ebtables-v2.0.8-2/Makefile
--- ebtables-v2.0.8-2-old/Makefile	2008-06-26 16:05:01.000000000 +0300
+++ ebtables-v2.0.8-2/Makefile	2008-06-26 16:06:13.000000000 +0300
@@ -7,12 +7,12 @@
 PROGDATE:=May\ 2007
 
 # default paths
-LIBDIR:=/usr/lib
-MANDIR:=/usr/local/man
-BINDIR:=/usr/local/sbin
+LIBDIR:=/lib/$(PROGNAME)
+MANDIR:=/usr/share/man
+BINDIR:=/sbin
 ETCDIR:=/etc
-INITDIR:=/etc/rc.d/init.d
-SYSCONFIGDIR:=/etc/sysconfig
+INITDIR:=/usr/share/doc/ebtables
+SYSCONFIGDIR:=/usr/share/doc/ebtables
 DESTDIR:=
 
 CFLAGS:=-Wall -Wunused
