Index: autossh-1.4c/Makefile.in
===================================================================
--- autossh-1.4c.orig/Makefile.in
+++ autossh-1.4c/Makefile.in
@@ -6,11 +6,11 @@ VER=		1.4c
 
 SSH=		@path_ssh@
 
-prefix=		@prefix@
+prefix=		${DESTDIR}@prefix@
 exec_prefix=	@exec_prefix@
 bindir=		@bindir@
-datadir=	@datadir@
-mandir=		@mandir@
+datadir=	${DESTDIR}@datadir@
+mandir=		${DESTDIR}@mandir@
 
 SRCDIR=		@srcdir@
 VPATH=		@srcdir@
@@ -31,7 +31,7 @@ all:		$(TARGET)
 
 
 $(TARGET):	$(OFILES)
-		$(CC) $(CPPFLAGS) -o $(TARGET) $(OFILES) $(LIBS)
+		$(CC) $(CPPFLAGS) $(LIBS) -o $(TARGET) $(OFILES) 
 
 clean:
 		- /bin/rm -f *.o *.a *.core *~
