--- Makefile.in.orig	2008-09-05 12:34:24.000000000 +0300
+++ Makefile.in	2008-09-05 12:35:26.000000000 +0300
@@ -202,7 +202,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-SUBDIRS = libxml++ docs scripts examples MSVC_Net2005
+SUBDIRS = libxml++ scripts MSVC_Net2005
 EXTRA_DIST = libxml++-2.6.pc.in libxml++.spec.in
 DIST_SUBDIRS = $(SUBDIRS) win32_msvc6
 
