--- Makefile.in.orig	2008-08-02 22:46:07.000000000 +0300
+++ Makefile.in	2008-08-02 23:50:17.000000000 +0300
@@ -8,11 +8,11 @@
 
 STATIC		:= @STATIC@
 
-doc_files	:= docs INSTALL CREDITS FAQ GNUGPL HELP README TODO AGREEMENT remote.help
+doc_files	:= INSTALL CREDITS FAQ GNUGPL HELP README TODO AGREEMENT remote.help
 
 FILES_TO_INSTALL := *.tcl hotmlog.htm amsn amsn-remote amsn-remote-CLI amsn.desktop langlist
 FILES_TO_INSTALL += $(doc_files)
-FILES_TO_INSTALL += desktop-icons lang skins utils/base64 utils/drawboard utils/framec utils/http2.4
+FILES_TO_INSTALL += lang skins utils/base64 utils/drawboard utils/framec utils/http2.4
 FILES_TO_INSTALL += utils/pixmapscroll utils/pixmapmenu utils/contentmanager
 FILES_TO_INSTALL += utils/scalable-bg utils/sha1 utils/snit utils/bwidget1.8.0 utils/dpbrowser
 FILES_TO_INSTALL += plugins utils/sexytile
@@ -187,7 +187,7 @@
 	mkdir -p $(DESTDIR)$(dstdir)/$(PACKAGE)
 	mkdir -p $(DESTDIR)$(slnkdir)
 	mkdir -p $(DESTDIR)$(dstdir)/applications/
-	mkdir -p $(DESTDIR)$(dstdir)/pixmaps/
+	mkdir -p $(DESTDIR)$(dstdir)/icons/hicolor/
 
 	@for p in $?; do \
 		mkdir -p `dirname $(DESTDIR)$(dstdir)/$(PACKAGE)/$$p`;\
@@ -203,8 +203,7 @@
 	ln -sf $(dstdir)/$(PACKAGE)/amsn-remote-CLI $(DESTDIR)$(slnkdir)/amsn-remote-CLI
 
 	cp $(srcdir)/amsn.desktop $(DESTDIR)$(dstdir)/applications/
-
-	ln -sf $(dstdir)/$(PACKAGE)/desktop-icons/48x48/apps/amsn.png $(DESTDIR)$(dstdir)/pixmaps/
+	cp -Rf $(srcdir)/desktop-icons/* $(DESTDIR)$(dstdir)/icons/hicolor/
 
 uninstall::
 	rm -Rf $(dstdir)/$(PACKAGE)
@@ -212,7 +211,6 @@
 	rm -f $(slnkdir)/amsn-remote
 	rm -f $(slnkdir)/amsn-remote-CLI
 	rm -f $(dstdir)/applications/amsn.desktop
-	rm -f $(dstdir)/pixmaps/amsn.png
 
 rpm: all
 	mkdir -p ./distrib
