#!/bin/sh

[ -d $HOME/.wine ] || wine

if [ "$1" = "-d" ] ;then
    unix_path=$(winepath "$2" | head -n 1)
    app_dir=$(dirname "$unix_path")
    cd "$app_dir"
    shift
fi

if [ "$1" = "-D" ] ;then
    cd "$2"
    shift 2
fi

if [ -z "$1" ]; then
    exec winefile
    exit
fi

app_name=$1
shift

exec wine "$app_name" $*
