--- Makefile.org	2007-11-28 00:13:21.000000000 +0200
+++ Makefile	2007-11-28 00:13:56.000000000 +0200
@@ -1,9 +1,9 @@
 VERSION=2.9.11
-CVSTAG = tmpwatch-$(subst .,_,$(VERSION))
-CVSROOT = $(shell cat CVS/Root)
+#CVSTAG = tmpwatch-$(subst .,_,$(VERSION))
+#CVSROOT = $(shell cat CVS/Root)
 OS_NAME=$(shell uname -s)
 
-CFLAGS=$(RPM_OPT_FLAGS) -W -Wall -DVERSION=\"$(VERSION)\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
+CFLAGS= -W -Wall -DVERSION=\"$(VERSION)\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
 
 ifeq ($(OS_NAME),HP-UX)
     ROOT=/
