#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2005-2007 TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

from pisi.actionsapi import autotools
from pisi.actionsapi import pisitools
from pisi.actionsapi import shelltools
from pisi.actionsapi import get

WorkDir = "linux-2.6.18"
EXTRAVERSION = 8
NoStrip = "/"

def setup():
    # Remove *.orig
    shelltools.system("find . -name \"*.orig\" | xargs rm -f")

    # Branding
    if EXTRAVERSION is not None:
        pisitools.dosed("Makefile", "EXTRAVERSION =.*", "EXTRAVERSION = .%s-%s-dom0" % (EXTRAVERSION, get.srcRELEASE()))
    else:
        pisitools.dosed("Makefile", "EXTRAVERSION =.*", "EXTRAVERSION = -%s-dom0" % get.srcRELEASE())

    autotools.make("oldconfig")

def build():
    autotools.make()

def install():
    suffix = "%s-%s-dom0" % (get.srcVERSION(), get.srcRELEASE())

    # install modules
    autotools.rawInstall("INSTALL_MOD_PATH=%s/" % get.installDIR(), "modules_install")

    # remove wrong symlinks
    pisitools.remove("/lib/modules/%s/source" % suffix)
    pisitools.remove("/lib/modules/%s/build" % suffix)

    # create true symlinks
    pisitools.dosym("/usr/src/linux-%s/" % suffix, "/lib/modules/%s/source" % suffix)
    pisitools.dosym("/usr/src/linux-%s/" % suffix, "/lib/modules/%s/build" % suffix)

    # insert System.map and bzImage
    pisitools.insinto("/boot/", "System.map", "System.map-%s" % suffix)
    pisitools.insinto("/boot/", "Module.symvers", "Module.symvers-%s" % suffix)
    pisitools.insinto("/boot/", "vmlinux", "kernel-%s" % suffix)

    # cp source to installDIR for kernel-source package
    pisitools.dodir("/usr/src")
    shelltools.copytree("../%s/" % WorkDir, "%s/usr/src/linux-%s/" % (get.installDIR(), suffix))

    # create linux symlink
    pisitools.dosym("/usr/src/linux-%s/" % suffix, "/usr/src/linux")

    # Clean the on in installDIR not compiled one and prepare kernel for module compiliation
    shelltools.cd("%s/usr/src/linux-%s" % (get.installDIR(), suffix))
    autotools.make("clean")
    autotools.make("modules_prepare")

    # generate mkinitramfs
    shelltools.system("/sbin/mkinitramfs kernel=%s --full --root-dir=%s --output=/%s/boot" % (suffix, get.installDIR(), get.installDIR()))

    # remove modules.* files, they will autogenerated on next boot
    pisitools.remove("/lib/modules/%s/modules.*" % suffix)
