--- flobopuyo-0.20.orig/Makefile	2004-10-09 01:41:12.000000000 +0300
+++ flobopuyo-0.20/Makefile	2009-02-19 12:24:27.000000000 +0200
@@ -12,9 +12,9 @@
 DEBUG_MODE=false
 
 # Unix/Linux settings
-PREFIX=/usr/local
-DATADIR=$(PREFIX)/share/games/flobopuyo
-INSTALL_BINDIR=$(DESTDIR)/$(PREFIX)/games
+PREFIX=/usr
+DATADIR=$(PREFIX)/share/flobopuyo
+INSTALL_BINDIR=$(DESTDIR)/$(PREFIX)/bin
 INSTALL_DATADIR=$(DESTDIR)/$(DATADIR)
 
 # Mac settings
