diff -ur mdadm-2.6.1.orig/Makefile mdadm-2.6.1/Makefile
--- mdadm-2.6.1.orig/Makefile	2007-02-22 05:59:28.000000000 +0200
+++ mdadm-2.6.1/Makefile	2007-05-09 01:47:38.531851176 +0300
@@ -31,7 +31,7 @@
 # e.g.  make CXFLAGS=-O to optimise
 TCC = tcc
 UCLIBC_GCC = $(shell for nm in i386-uclibc-linux-gcc i386-uclibc-gcc; do which $$nm > /dev/null && { echo $$nm ; exit; } ; done; echo false No uclibc found )
-DIET_GCC = diet gcc
+DIET_GCC = gcc
 
 KLIBC=/home/src/klibc/klibc-0.77
 
@@ -39,7 +39,7 @@
 
 CC = $(CROSS_COMPILE)gcc
 CXFLAGS = -ggdb
-CWFLAGS = -Wall -Werror -Wstrict-prototypes
+CWFLAGS = -Wall -Wstrict-prototypes
 
 ifdef DEBIAN
 CPPFLAGS= -DDEBIAN
@@ -94,15 +94,17 @@
 # mdadm.tcc doesn't work..
 
 mdadm : $(OBJS)
-	$(CC) $(LDFLAGS) -o mdadm $(OBJS) $(LDLIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o mdadm $(OBJS) $(LDLIBS)
 
 mdadm.static : $(OBJS) $(STATICOBJS)
-	$(CC) $(LDFLAGS) -static -o mdadm.static $(OBJS) $(STATICOBJS)
+	$(CC) $(CFLAGS) $(LDFLAGS) -static -o mdadm.static $(OBJS) $(STATICOBJS)
 
 mdadm.tcc : $(SRCS) mdadm.h
+	rm -f $(OBJS)
 	$(TCC) -o mdadm.tcc $(SRCS)
 
 mdadm.uclibc : $(SRCS) mdadm.h
+	rm -f $(OBJS) $(STATICOBJS)
 	$(UCLIBC_GCC) -DUCLIBC -DHAVE_STDINT_H -o mdadm.uclibc $(SRCS) $(STATICSRC)
 
 mdadm.klibc : $(SRCS) mdadm.h
@@ -113,15 +115,15 @@
 	$(CC) $(CXFLAGS) $(LDFLAGS) -o test_stripe -DMAIN restripe.c
 
 mdassemble : $(ASSEMBLE_SRCS) mdadm.h
-	rm -f $(OBJS)
-	$(DIET_GCC) $(ASSEMBLE_FLAGS) -o mdassemble $(ASSEMBLE_SRCS)  $(STATICSRC)
+	rm -f $(OBJS) $(STATICOBJS)
+	$(CC) $(ASSEMBLE_FLAGS) $(LDFLAGS) -DHAVE_STDINT_H -o mdassemble.static $(ASSEMBLE_SRCS) $(STATICSRC)
 
-mdassemble.static : $(ASSEMBLE_SRCS) mdadm.h
-	rm -f $(OBJS)
-	$(CC) $(LDFLAGS) $(ASSEMBLE_FLAGS) -static -DHAVE_STDINT_H -o mdassemble.static $(ASSEMBLE_SRCS) $(STATICSRC)
+mdassemble.static : $(ASSEMBLE_SRCS) $(STATICSRC) mdadm.h
+	rm -f $(OBJS) $(STATICOBJS)
+	$(CC) $(ASSEMBLE_FLAGS) $(LDFLAGS) -static -DHAVE_STDINT_H -o mdassemble.static $(ASSEMBLE_SRCS) $(STATICSRC)
 
-mdassemble.uclibc : $(ASSEMBLE_SRCS) mdadm.h
-	rm -f $(OJS)
+mdassemble.uclibc : $(ASSEMBLE_SRCS) $(STATICSRC) mdadm.h
+	rm -f $(OBJS) $(STATICOBJS)
 	$(UCLIBC_GCC) $(ASSEMBLE_FLAGS) -DUCLIBC -DHAVE_STDINT_H -static -o mdassemble.uclibc $(ASSEMBLE_SRCS) $(STATICSRC)
 
 # This doesn't work
@@ -146,25 +148,28 @@
 sha1.o : sha1.c sha1.h md5.h
 	$(CC) $(CFLAGS) -DHAVE_STDINT_H -o sha1.o -c sha1.c
 
-install : mdadm install-man
-	$(INSTALL) -D $(STRIP) -m 755 mdadm $(DESTDIR)$(BINDIR)/mdadm
+install : mdadm mdadm.static mdassemble.static install-man
+	$(INSTALL) -D -m 755 mdadm $(DESTDIR)$(BINDIR)/mdadm
+	$(INSTALL) -D -m 755 mdadm.static $(DESTDIR)$(BINDIR)/mdadm.static
+	$(INSTALL) -D -m 755 mdassemble.static $(DESTDIR)$(BINDIR)/mdassemble.static
 
 install-static : mdadm.static install-man
-	$(INSTALL) -D $(STRIP) -m 755 mdadm.static $(DESTDIR)$(BINDIR)/mdadm
+	$(INSTALL) -D -m 755 mdadm.static $(DESTDIR)$(BINDIR)/mdadm
 
 install-tcc : mdadm.tcc install-man
-	$(INSTALL) -D $(STRIP) -m 755 mdadm.tcc $(DESTDIR)$(BINDIR)/mdadm
+	$(INSTALL) -D -m 755 mdadm.tcc $(DESTDIR)$(BINDIR)/mdadm
 
 install-uclibc : mdadm.uclibc install-man
-	$(INSTALL) -D $(STRIP) -m 755 mdadm.uclibc $(DESTDIR)$(BINDIR)/mdadm
+	$(INSTALL) -D -m 755 mdadm.uclibc $(DESTDIR)$(BINDIR)/mdadm
 
 install-klibc : mdadm.klibc install-man
-	$(INSTALL) -D $(STRIP) -m 755 mdadm.klibc $(DESTDIR)$(BINDIR)/mdadm
+	$(INSTALL) -D -m 755 mdadm.klibc $(DESTDIR)$(BINDIR)/mdadm
 
-install-man: mdadm.8 md.4 mdadm.conf.5
-	$(INSTALL) -D -m 644 mdadm.8 $(DESTDIR)$(MAN8DIR)/mdadm.8
-	$(INSTALL) -D -m 644 md.4 $(DESTDIR)$(MAN4DIR)/md.4
-	$(INSTALL) -D -m 644 mdadm.conf.5 $(DESTDIR)$(MAN5DIR)/mdadm.conf.5
+install-man: mdadm.8 mdassemble.8 md.4 mdadm.conf.5
+	$(INSTALL) -Dp -m 644 mdadm.8 $(DESTDIR)$(MAN8DIR)/mdadm.8
+	$(INSTALL) -Dp -m 644 mdassemble.8 $(DESTDIR)$(MAN8DIR)/mdassemble.8
+	$(INSTALL) -Dp -m 644 md.4 $(DESTDIR)$(MAN4DIR)/md.4
+	$(INSTALL) -Dp -m 644 mdadm.conf.5 $(DESTDIR)$(MAN5DIR)/mdadm.conf.5
 
 uninstall:
 	rm -f $(DESTDIR)$(MAN8DIR)/mdadm.8 md.4 $(DESTDIR)$(MAN4DIR)/md.4 $(DESTDIR)$(MAN5DIR)/mdadm.conf.5 $(DESTDIR)$(BINDIR)/mdadm
Yalnızca mdadm-2.6.1'da: Makefile.orig
