diff -ur ladspa_sdk.orig/src/makefile ladspa_sdk/src/makefile
--- ladspa_sdk.orig/src/makefile	2002-07-06 20:34:20.000000000 +0300
+++ ladspa_sdk/src/makefile	2006-06-06 01:34:19.000000000 +0300
@@ -5,9 +5,9 @@
 # Change these if you want to install somewhere else. In particularly
 # you may wish to remove the middle "local/" part of each entry.
 
-INSTALL_PLUGINS_DIR	=	/usr/local/lib/ladspa/
+INSTALL_PLUGINS_DIR	=	/usr/lib/ladspa/
 INSTALL_INCLUDE_DIR	=	/usr/include/
-INSTALL_BINARY_DIR	=	/usr/local/bin/
+INSTALL_BINARY_DIR	=	/usr/bin/
 
 ###############################################################################
 #
@@ -47,24 +47,24 @@
 # TARGETS
 #
 
-test:	/tmp/test.wav ../snd/noise.wav always
-	@echo ---------------------------------------------
-	@echo First listen to the white noise input signal:
-	@echo ---------------------------------------------
-	play ../snd/noise.wav
-	@echo -------------------------
-	@echo Compare to plugin output.
-	@echo -------------------------
-	@echo Should be a noise band around 6000Hz, repeated quietly after 1s.
-	play /tmp/test.wav
-
-install:	targets
-	-mkdirhier	$(INSTALL_PLUGINS_DIR)				\
-			$(INSTALL_INCLUDE_DIR)				\
-			$(INSTALL_BINARY_DIR)
-	cp ../plugins/* $(INSTALL_PLUGINS_DIR)
-	cp ladspa.h $(INSTALL_INCLUDE_DIR)
-	cp ../bin/* $(INSTALL_BINARY_DIR)
+#test:	/tmp/test.wav ../snd/noise.wav always
+#	@echo ---------------------------------------------
+#	@echo First listen to the white noise input signal:
+#	@echo ---------------------------------------------
+#	play ../snd/noise.wav
+#	@echo -------------------------
+#	@echo Compare to plugin output.
+#	@echo -------------------------
+#	@echo Should be a noise band around 6000Hz, repeated quietly after 1s.
+#	play /tmp/test.wav
+
+#install:	targets
+#	-mkdirhier	$(INSTALL_PLUGINS_DIR)				\
+#			$(INSTALL_INCLUDE_DIR)				\
+#			$(INSTALL_BINARY_DIR)
+#	cp ../plugins/* $(INSTALL_PLUGINS_DIR)
+#	cp ladspa.h $(INSTALL_INCLUDE_DIR)
+#	cp ../bin/* $(INSTALL_BINARY_DIR)
 
 /tmp/test.wav:	targets ../snd/noise.wav
 	../bin/listplugins
@@ -74,7 +74,7 @@
 	echo ; ../bin/analyseplugin -l ../plugins/sine.so ; echo
 	../bin/analyseplugin ../plugins/amp.so
 	../bin/analyseplugin ../plugins/noise.so
-	time ../bin/applyplugin	-s 1					\
+	../bin/applyplugin  -s 1				    	\
 				../snd/noise.wav /tmp/test.wav		\
 				../plugins/filter.so lpf 500		\
 				../plugins/filter.so lpf 500		\
