--- /var/pisi/vegastrike-0.5.0-1/work/vegastrike-0.5.0/Makefile.am	2009-03-10 22:56:25.000000000 +0200
+++ Makefile.am	2009-03-10 23:01:59.000000000 +0200
@@ -480,14 +480,6 @@
   GTKUTILS_PROG=
 endif
 
-if VS_MAKE_NO_CLIENT
-  CLIENT_PROG=
-else
-  CLIENT_PROG= \
-    vegastrike \
-    base_maker
-endif
-
 bin_PROGRAMS = \
   $(CLIENT_PROG) \
   asteroidgen \
@@ -499,6 +491,8 @@
   vegaserver \
   vsrextract \
   vsrmake \
+  base_maker \
+  vegastrike \
   $(GTKUTILS_PROG)
 
 
@@ -993,7 +987,7 @@
   src/python/briefing_wrapper.cpp
 
 
-pkgdatadir = $(prefix)/objconv
+pkgdatadir = $(prefix)/share/vegastrike/objconv
 pkgdata_DATA = objconv/3ds2xml objconv/obj2xml objconv/wcp2xml
 EXTRA_DIST += $(pkgdata_DATA)
 
