#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2005, 2009 TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

from pisi.actionsapi import autotools
from pisi.actionsapi import pisitools
from pisi.actionsapi import shelltools
from pisi.actionsapi import get

WorkDir = "linux-2.6.25"
EXTRAVERSION = "20"
NoStrip = "/"

def setup():
    # Remove *.orig
    shelltools.system("find . -name \"*.orig\" | xargs rm -f")

    # Branding
    if EXTRAVERSION is not None:
        pisitools.dosed("Makefile", "EXTRAVERSION =.*", "EXTRAVERSION = .%s-%s-debug" % (EXTRAVERSION, get.srcRELEASE()))
    else:
        pisitools.dosed("Makefile", "EXTRAVERSION =.*", "EXTRAVERSION = -%s-debug" % get.srcRELEASE())

    autotools.make("oldconfig")

def build():
    autotools.make()

def install():
    suffix = "%s-%s-debug" % (get.srcVERSION(), get.srcRELEASE())

    # install modules
    autotools.rawInstall("INSTALL_MOD_PATH=%s/" % get.installDIR(), "modules_install")

    # remove wrong symlinks
    pisitools.remove("/lib/modules/%s/source" % suffix)
    pisitools.remove("/lib/modules/%s/build" % suffix)

    # create true symlinks
    pisitools.dosym("/usr/src/linux-%s/" % suffix, "/lib/modules/%s/source" % suffix)
    pisitools.dosym("/usr/src/linux-%s/" % suffix, "/lib/modules/%s/build" % suffix)

    # insert System.map, bzImage and Module.symvers
    pisitools.insinto("/lib/modules/%s/" % suffix, "System.map")
    pisitools.insinto("/lib/modules/%s/" % suffix, "Module.symvers")
    pisitools.insinto("/boot/", "arch/x86/boot/bzImage", "kernel-%s" % suffix)

    # Insert vmlinux into /boot to generate kernel-debug package for profiling with oprofile
    pisitools.insinto("/boot", "vmlinux", "vmlinux-%s" % suffix)

    # cp source to installDIR for kernel-source package
    pisitools.dodir("/usr/src")
    shelltools.copytree("../%s/" % WorkDir, "%s/usr/src/linux-%s/" % (get.installDIR(), suffix))

    # Clean the on in installDIR not compiled one and prepare kernel for module compiliation
    shelltools.cd("%s/usr/src/linux-%s" % (get.installDIR(), suffix))
    autotools.make("clean")
    autotools.make("modules_prepare")

    # generate mkinitramfs
    shelltools.system("/sbin/mkinitramfs kernel=%s --full --root-dir=%s --output=/%s/boot" % (suffix, get.installDIR(), get.installDIR()))

    # remove modules.* files, they will autogenerated on next boot
    pisitools.remove("/lib/modules/%s/modules.*" % suffix)
