diff -Nur tmpwatch-2.9.13.orig/Makefile tmpwatch-2.9.13/Makefile
--- tmpwatch-2.9.13.orig/Makefile	2008-02-23 03:17:28.000000000 +0200
+++ tmpwatch-2.9.13/Makefile	2008-04-25 20:57:53.000000000 +0300
@@ -2,7 +2,7 @@
 HGTAG = 'tmpwatch-$(VERSION)'
 OS_NAME=$(shell uname -s)
 
-CFLAGS=$(RPM_OPT_FLAGS) -W -Wall -DVERSION=\"$(VERSION)\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
+#CFLAGS=$(RPM_OPT_FLAGS) -W -Wall -DVERSION=\"$(VERSION)\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
 
 ifeq ($(OS_NAME),HP-UX)
     ROOT=/
