Index: system-config-printer-1.1.3/Makefile.in
===================================================================
--- system-config-printer-1.1.3.orig/Makefile.in
+++ system-config-printer-1.1.3/Makefile.in
@@ -944,7 +944,7 @@ info: info-recursive
 
 info-am:
 
-install-data-am: install-dbusDATA install-desktopDATA install-man \
+install-data-am: install-dbusDATA install-man \
 	install-nobase_pkgdataDATA install-nobase_pkgdataSCRIPTS
 
 install-dvi: install-dvi-recursive
