pref("browser.display.screen_resolution", 0);
pref("browser.display.show_image_placeholders", false);
pref("browser.display.use_document_fonts", 1);
pref("browser.display.use_system_colors", true);
pref("browser.link.open_external", 3);
pref("browser.tabs.autoHide", false);
pref("browser.startup.page", 3);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.throbber.url", "resource:/browserconfig.properties");
pref("startup.homepage_override_url", "resource:/browserconfig.properties");
pref("spellchecker.dictionary", "tr-TR");
pref("browser.urlbar.clickSelectsAll", true);
pref("browser.backspace_action", 0);
pref("general.autoScroll", true);
pref("general.smoothScroll", true);
pref("middlemouse.contentLoadURL", false);
pref("network.prefetch-next", false);
pref("network.protocol-handler.expose.callto", true);
pref("network.protocol-handler.app.callto", "skype");
pref("network.protocol-handler.expose.lastfm", true);
pref("network.protocol-handler.app.lastfm","lastfm");
pref("network.protocol-handler.expose.mailto", true);
pref("network.protocol-handler.app.mailto", "kmail-firefox");
pref("network.protocol-handler.expose.mms", true);
pref("network.protocol-handler.app.mms", "kaffeine");
pref("font.minimum-size.null", 12);
pref("font.minimum-size.tr", 12);
pref("font.minimum-size.x-central-euro", 12);
pref("font.minimum-size.x-unicode", 12);
pref("font.minimum-size.x-user-def", 12);
pref("font.minimum-size.x-western", 12);
pref("font.size.fixed.null", 12);
pref("font.size.variable.null", 12);
pref("font.size.variable.tr", 12);
pref("font.size.variable.x-unicode", 12);
pref("font.size.variable.x-western", 12);
pref("font.default.null", "sans-serif");
pref("font.name.monospace.null", "DejaVu Sans Mono");
pref("font.name.monospace.tr", "DejaVu Sans Mono");
pref("font.name.monospace.x-central-euro", "DejaVu Sans Mono");
pref("font.name.monospace.x-unicode", "DejaVu Sans Mono");
pref("font.name.monospace.x-user-def", "DejaVu Sans Mono");
pref("font.name.monospace.x-western", "DejaVu Sans Mono");
pref("font.name.sans-serif.null", "DejaVu Sans");
pref("font.name.sans-serif.tr", "DejaVu Sans");
pref("font.name.sans-serif.x-central-euro", "DejaVu Sans");
pref("font.name.sans-serif.x-unicode", "DejaVu Sans");
pref("font.name.sans-serif.x-user-def", "DejaVu Sans");
pref("font.name.sans-serif.x-western", "DejaVu Sans");
pref("font.name.serif.null", "DejaVu Serif");
pref("font.name.serif.tr", "DejaVu Sans");
pref("font.name.serif.x-central-euro", "DejaVu Sans");
pref("font.name.serif.x-unicode", "DejaVu Sans");
pref("font.name.serif.x-user-def", "DejaVu Sans");
pref("font.name.serif.x-western", "DejaVu Sans");
// pref("font.language.group", "tr");
// pref("intl.charset.default", "UTF-8");
// pref("intl.charsetmenu.browser.cache", "UTF-8");
pref("general.useragent.vendor", "Pardus");
pref("general.useragent.vendorSub", "2007");

