#!/bin/sh

export LC_ALL=C

if [ "$2" = "down" ]; then
	if ! /sbin/ip route ls | grep -q ^default &&
	   [ -f /var/lock/subsys/iscsi ]; then
		/bin/service iscsi stop
	fi
fi

if [ "$2" = "up" ]; then
	if /sbin/ip -o route show dev "$1" | grep -q '^default' &&
	   /sbin/chkconfig iscsi; then
		/bin/service iscsi start
	fi
fi
