#!/bin/sh

[ -d $HOME/.wine ] || wine

change_workdir=false

if [ "$1" = "-d" ] ;then
    change_workdir=true
    shift
fi

if [ "$1" = "-D" ] ;then
    cd "$2"
    shift 2
fi

if [ -z "$1" ]; then
    exec winefile
    exit
fi

app_name=$1
shift

if [ -x /usr/bin/kio-to-local ] ;then
    app_name=$(/usr/bin/kio-to-local /bin/echo "$app_name")
fi

if [ change_workdir ] ;then
    unix_path=$(winepath "$app_name" | head -n 1)
    app_dir=$(dirname "$unix_path")
    cd "$app_dir"
fi

app_name=$(winepath -w "$app_name")

exec wine start.exe "$app_name" $*
