#!/bin/bash
# if the system is configured for 855/915resolution, we first patch the BIOS
# to avoid that the X server crashes after switching back to X

case $1 in
	thaw)
		echo "patching video bios..."
		/sbin/zorg --intelfix
		;;
esac

exit 0
