--- Makefile.org	2008-04-19 01:17:37.000000000 +0300
+++ Makefile	2008-04-19 01:20:19.000000000 +0300
@@ -41,7 +41,7 @@
 DESTDIR :=
 
 # This is the prefix that will be used for almost all directories below.
-PREFIX := /usr/local
+PREFIX := /usr
 
 # Your C compiler
 CC := gcc
@@ -79,7 +79,7 @@
 MACHINE := $(shell uname -m)
 
 # Extra non-default programs to build; e.g., sensord
-# PROG_EXTRA := sensord
+PROG_EXTRA := sensord
 
 # Set these to add preprocessor or compiler flags, or use
 # environment variables
