#!/bin/bash

MAIN="DigiBand"

DATADIR="/usr/share/$MAIN"

TARGET="$HOME/.$MAIN"

TOSYMLINK="Noteskins Songs Themes"

TOCOPY="Data"

if [ ! -e "$TARGET" ]; then
        mkdir "$TARGET"
fi
for d in $TOSYMLINK; do
        if [ ! -e "$TARGET/$d" ] ; then
                ln -s "$DATADIR/$d" "$TARGET/$d"
        fi
done

for f in $TOCOPY; do
        if [ ! -e "$TARGET/$f" ] ; then
                cp -R "$DATADIR/$f" "$TARGET/"
        fi
done

cd "$TARGET"

exec /usr/bin/$MAIN.bin "$@"
