#!/bin/bash
#
# Stefan Seyfried, SUSE Linux Products GmbH, 2006
# mostly taken from the powersave project

#############################################################
# triggers the ACPI fan(s) after resume. Since ACPI drivers
# have no suspend support, this is sometimes necessary.
# see http://article.gmane.org/gmane.linux.acpi.devel/16643
kick-fan()
{
	local FAN DUMMY STATE 
	for FAN in /proc/acpi/fan/*/state; do
		[ ! -e $FAN ] && continue
		read DUMMY STATE < $FAN
		if [ "$STATE" = "on" ]; then
			echo "kicking $FAN"
			echo -n 3 > $FAN
			echo -n 0 > $FAN
		fi
	done
}

case $1 in
	thaw|resume)
		kick-fan
		;;
esac

exit 0
