diff -Naur truecrypt-6.3a-source.orig/Makefile truecrypt-6.3a-source/Makefile
--- truecrypt-6.3a-source.orig/Makefile	2010-01-17 21:32:21.000000000 +0200
+++ truecrypt-6.3a-source/Makefile	2010-01-17 21:40:19.000000000 +0200
@@ -33,13 +33,13 @@
 export CXX ?= g++
 export RANLIB ?= ranlib
 
-export CFLAGS := -Wall
-export CXXFLAGS := -Wall -Wno-unused-parameter
+export CFLAGS :+= -Wall
+export CXXFLAGS :+= -Wall -Wno-unused-parameter
 C_CXX_FLAGS := -MMD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -I$(BASE_DIR) -I$(BASE_DIR)/Crypto
 
-export LFLAGS :=
+export LFLAGS :=$(LDFLAGS)
 
-export PKG_CONFIG_PATH ?= /usr/local/lib/pkgconfig
+export PKG_CONFIG_PATH ?= /usr/lib/pkgconfig
 
 export WX_CONFIG ?= wx-config
 export WX_CONFIG_ARGS := --unicode
